在release和hotfix分支finish -r时自动在gitlab上创建merge request,指派给项目的master.需要先在git init中配置

diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -42,12 +42,15 @@ init() {
   gitflow_load_settings
   VERSION_PREFIX=$(eval "echo `git config --get gitflow.prefix.versiontag`")
   PREFIX=$(git config --get gitflow.prefix.release)
+  GITLAB_HOST=$(git config --get gitlab.host)
+  GITLAB_PROJECTID=$(git config --get gitlab.projectid)
+  GITLAB_TOKEN=$(git config --get gitlab.token)
 }
 
 usage() {
 	echo "usage: git flow release [list] [-v]"
 	echo "       git flow release start [-F] <version> [<base>]"
-	echo "       git flow release finish [-FsumpkS] <version>"
+	echo "       git flow release finish [-FsumpkSr] <version>"
 	echo "       git flow release publish <name>"
 	echo "       git flow release track <name>"
 }
@@ -197,6 +200,7 @@ cmd_finish() {
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	DEFINE_boolean notag false "don't tag this release" n
 	DEFINE_boolean squash false "squash release during merge" S
+	DEFINE_boolean mergerequest false "create merge request on GITLAB" r
 
 	parse_args "$@"
 	require_version_arg
@@ -284,7 +288,8 @@ cmd_finish() {
 		git_do branch -d "$BRANCH"
 	fi
 
-	if flag push; then
+	
+	if flag push || flag mergerequest; then
 		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
 			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
 		git_do push "$ORIGIN" "$MASTER_BRANCH" || \
@@ -293,8 +298,35 @@ cmd_finish() {
 			git_do push --tags "$ORIGIN" || \
 			  die "Could not push tags to $ORIGIN."
 		fi
-		git_do push "$ORIGIN" :"$BRANCH" || \
-			die "Could not delete the remote $BRANCH in $ORIGIN."
+		##git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+	fi
+	
+	
+	# create merge request on GITLAB
+	# API: 
+	# POST http://GITLAB_HOST/api/v3/projects/:id/merge_requests?private_token=
+	# source_branch=master&target_branch=product&assignee_id=&title=
+	# 
+	# Implements:
+	# first we'll get all members from this project
+	# then check if someone has the "master" access (access_level=40)
+	# and call "create merge" for each master
+	
+	if flag mergerequest; then
+		members=$(curl -s "http://$GITLAB_HOST/api/v3/projects/$GITLAB_PROJECTID/members?private_token=$GITLAB_TOKEN" ||\
+			 die "ERROR: check your GITLAB host: $GITLAB_HOST. ")
+		# check if unauthorized
+		not_authrozied=$(echo "$members" |grep "401" |wc -l)
+		[ $not_authrozied -gt 0 ] && die "401 Unauthorized: check your GITLAB private token: $GITLAB_TOKEN "
+
+		master_ids=$(echo "$members"|json-parse|\
+			awk '{if($1~/id/){a[substr($1,2,index($1,",")-2)]=$2}else if($1~/access_level/ && $2==40)\
+				{print a[substr($1,2,index($1,",")-2)]}}')
+
+		for master_id in $master_ids; do
+			curl -s -X POST -d "source_branch=$MASTER_BRANCH&target_branch=product&assignee_id=$master_id&title=$BRANCH" \
+				"http://$GITLAB_HOST/api/v3/projects/$GITLAB_PROJECTID/merge_requests?private_token=$GITLAB_TOKEN"
+		done
 	fi
 
 	echo
@@ -310,9 +342,12 @@ cmd_finish() {
 	else
 		echo "- Release branch '$BRANCH' has been deleted"
 	fi
-	if flag push; then
+	if flag push || flag mergerequest; then
 		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
 		echo "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
+	fi
+	if flag mergerequest; then
+		echo "- Merge request was auto created on GITLAB."
 	fi
 	echo
 }
